UHF-1083: Unit map
City-of-Helsinki/drupal-helfi-sote pull request #24
Opened 2021-06-14 12:39 UTC by teroelonen

Testing instructions are here: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/108

Also check these PRs:
https://github.com/City-of-Helsinki/drupal-hdbt/pull/103
https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/36
https://github.com/City-of-Helsinki/drupal-helfi/pull/135

2021-06-14 14:44 UTC, khalima requested changes
Check the duplicated content in user roles.

2021-06-14 14:44 UTC, khalima commented on conf/cmi/user.role.admin.yml
> +  - 'access tpr_service overview'
Are these duplicated?

2021-06-14 14:44 UTC, khalima commented on conf/cmi/user.role.anonymous.yml
> +  - 'view tpr_service'
Duplicated?

2021-06-14 14:44 UTC, khalima commented on conf/cmi/user.role.authenticated.yml
> +  - 'view tpr_service'
Duplicated?

2021-06-15 15:44 UTC, teroelonen commented on conf/cmi/user.role.admin.yml
> +  - 'access tpr_service overview'
True.dat! Fixed.

2021-06-15 15:44 UTC, teroelonen commented on conf/cmi/user.role.anonymous.yml
> +  - 'view tpr_service'
Fixed.

2021-06-15 15:44 UTC, teroelonen commented on conf/cmi/user.role.authenticated.yml
> +  - 'view tpr_service'
Fixed.

2021-06-16 06:45 UTC, khalima approved these changes
Good to go! 👍

2021-06-16 06:50 UTC, merged